// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/alignments.proto

package expressd.protobuf;

public final class Alignments {
  private Alignments() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadAlignmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool first = 1;
    boolean hasFirst();
    boolean getFirst();
    
    // optional uint32 left_pos = 2;
    boolean hasLeftPos();
    int getLeftPos();
    
    // optional uint32 right_pos = 3;
    boolean hasRightPos();
    int getRightPos();
    
    // optional bytes mismatch_indices = 4;
    boolean hasMismatchIndices();
    com.google.protobuf.ByteString getMismatchIndices();
    
    // optional bytes mismatch_nucs = 5;
    boolean hasMismatchNucs();
    com.google.protobuf.ByteString getMismatchNucs();
  }
  public static final class ReadAlignment extends
      com.google.protobuf.GeneratedMessage
      implements ReadAlignmentOrBuilder {
    // Use ReadAlignment.newBuilder() to construct.
    private ReadAlignment(Builder builder) {
      super(builder);
    }
    private ReadAlignment(boolean noInit) {}
    
    private static final ReadAlignment defaultInstance;
    public static ReadAlignment getDefaultInstance() {
      return defaultInstance;
    }
    
    public ReadAlignment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return expressd.protobuf.Alignments.internal_static_proto_ReadAlignment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return expressd.protobuf.Alignments.internal_static_proto_ReadAlignment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool first = 1;
    public static final int FIRST_FIELD_NUMBER = 1;
    private boolean first_;
    public boolean hasFirst() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getFirst() {
      return first_;
    }
    
    // optional uint32 left_pos = 2;
    public static final int LEFT_POS_FIELD_NUMBER = 2;
    private int leftPos_;
    public boolean hasLeftPos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLeftPos() {
      return leftPos_;
    }
    
    // optional uint32 right_pos = 3;
    public static final int RIGHT_POS_FIELD_NUMBER = 3;
    private int rightPos_;
    public boolean hasRightPos() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRightPos() {
      return rightPos_;
    }
    
    // optional bytes mismatch_indices = 4;
    public static final int MISMATCH_INDICES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString mismatchIndices_;
    public boolean hasMismatchIndices() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getMismatchIndices() {
      return mismatchIndices_;
    }
    
    // optional bytes mismatch_nucs = 5;
    public static final int MISMATCH_NUCS_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString mismatchNucs_;
    public boolean hasMismatchNucs() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getMismatchNucs() {
      return mismatchNucs_;
    }
    
    private void initFields() {
      first_ = false;
      leftPos_ = 0;
      rightPos_ = 0;
      mismatchIndices_ = com.google.protobuf.ByteString.EMPTY;
      mismatchNucs_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFirst()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, first_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, leftPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, rightPos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, mismatchIndices_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, mismatchNucs_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, first_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, leftPos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, rightPos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, mismatchIndices_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, mismatchNucs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.ReadAlignment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(expressd.protobuf.Alignments.ReadAlignment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements expressd.protobuf.Alignments.ReadAlignmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return expressd.protobuf.Alignments.internal_static_proto_ReadAlignment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return expressd.protobuf.Alignments.internal_static_proto_ReadAlignment_fieldAccessorTable;
      }
      
      // Construct using expressd.protobuf.Alignments.ReadAlignment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        first_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        leftPos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rightPos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        mismatchIndices_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        mismatchNucs_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return expressd.protobuf.Alignments.ReadAlignment.getDescriptor();
      }
      
      public expressd.protobuf.Alignments.ReadAlignment getDefaultInstanceForType() {
        return expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
      }
      
      public expressd.protobuf.Alignments.ReadAlignment build() {
        expressd.protobuf.Alignments.ReadAlignment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private expressd.protobuf.Alignments.ReadAlignment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        expressd.protobuf.Alignments.ReadAlignment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public expressd.protobuf.Alignments.ReadAlignment buildPartial() {
        expressd.protobuf.Alignments.ReadAlignment result = new expressd.protobuf.Alignments.ReadAlignment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.first_ = first_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leftPos_ = leftPos_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rightPos_ = rightPos_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mismatchIndices_ = mismatchIndices_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mismatchNucs_ = mismatchNucs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof expressd.protobuf.Alignments.ReadAlignment) {
          return mergeFrom((expressd.protobuf.Alignments.ReadAlignment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(expressd.protobuf.Alignments.ReadAlignment other) {
        if (other == expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance()) return this;
        if (other.hasFirst()) {
          setFirst(other.getFirst());
        }
        if (other.hasLeftPos()) {
          setLeftPos(other.getLeftPos());
        }
        if (other.hasRightPos()) {
          setRightPos(other.getRightPos());
        }
        if (other.hasMismatchIndices()) {
          setMismatchIndices(other.getMismatchIndices());
        }
        if (other.hasMismatchNucs()) {
          setMismatchNucs(other.getMismatchNucs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFirst()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              first_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leftPos_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rightPos_ = input.readUInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              mismatchIndices_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              mismatchNucs_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool first = 1;
      private boolean first_ ;
      public boolean hasFirst() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getFirst() {
        return first_;
      }
      public Builder setFirst(boolean value) {
        bitField0_ |= 0x00000001;
        first_ = value;
        onChanged();
        return this;
      }
      public Builder clearFirst() {
        bitField0_ = (bitField0_ & ~0x00000001);
        first_ = false;
        onChanged();
        return this;
      }
      
      // optional uint32 left_pos = 2;
      private int leftPos_ ;
      public boolean hasLeftPos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLeftPos() {
        return leftPos_;
      }
      public Builder setLeftPos(int value) {
        bitField0_ |= 0x00000002;
        leftPos_ = value;
        onChanged();
        return this;
      }
      public Builder clearLeftPos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leftPos_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 right_pos = 3;
      private int rightPos_ ;
      public boolean hasRightPos() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRightPos() {
        return rightPos_;
      }
      public Builder setRightPos(int value) {
        bitField0_ |= 0x00000004;
        rightPos_ = value;
        onChanged();
        return this;
      }
      public Builder clearRightPos() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rightPos_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes mismatch_indices = 4;
      private com.google.protobuf.ByteString mismatchIndices_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMismatchIndices() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getMismatchIndices() {
        return mismatchIndices_;
      }
      public Builder setMismatchIndices(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        mismatchIndices_ = value;
        onChanged();
        return this;
      }
      public Builder clearMismatchIndices() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mismatchIndices_ = getDefaultInstance().getMismatchIndices();
        onChanged();
        return this;
      }
      
      // optional bytes mismatch_nucs = 5;
      private com.google.protobuf.ByteString mismatchNucs_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMismatchNucs() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getMismatchNucs() {
        return mismatchNucs_;
      }
      public Builder setMismatchNucs(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mismatchNucs_ = value;
        onChanged();
        return this;
      }
      public Builder clearMismatchNucs() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mismatchNucs_ = getDefaultInstance().getMismatchNucs();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:expressd.protobuf.ReadAlignment)
    }
    
    static {
      defaultInstance = new ReadAlignment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:expressd.protobuf.ReadAlignment)
  }
  
  public interface FragmentAlignmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 target_id = 1;
    boolean hasTargetId();
    int getTargetId();
    
    // optional uint32 length = 2;
    boolean hasLength();
    int getLength();
    
    // optional .expressd.protobuf.ReadAlignment read_l = 3;
    boolean hasReadL();
    expressd.protobuf.Alignments.ReadAlignment getReadL();
    expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadLOrBuilder();
    
    // optional .expressd.protobuf.ReadAlignment read_r = 4;
    boolean hasReadR();
    expressd.protobuf.Alignments.ReadAlignment getReadR();
    expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadROrBuilder();
  }
  public static final class FragmentAlignment extends
      com.google.protobuf.GeneratedMessage
      implements FragmentAlignmentOrBuilder {
    // Use FragmentAlignment.newBuilder() to construct.
    private FragmentAlignment(Builder builder) {
      super(builder);
    }
    private FragmentAlignment(boolean noInit) {}
    
    private static final FragmentAlignment defaultInstance;
    public static FragmentAlignment getDefaultInstance() {
      return defaultInstance;
    }
    
    public FragmentAlignment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return expressd.protobuf.Alignments.internal_static_proto_FragmentAlignment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return expressd.protobuf.Alignments.internal_static_proto_FragmentAlignment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 target_id = 1;
    public static final int TARGET_ID_FIELD_NUMBER = 1;
    private int targetId_;
    public boolean hasTargetId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTargetId() {
      return targetId_;
    }
    
    // optional uint32 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getLength() {
      return length_;
    }
    
    // optional .expressd.protobuf.ReadAlignment read_l = 3;
    public static final int READ_L_FIELD_NUMBER = 3;
    private expressd.protobuf.Alignments.ReadAlignment readL_;
    public boolean hasReadL() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public expressd.protobuf.Alignments.ReadAlignment getReadL() {
      return readL_;
    }
    public expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadLOrBuilder() {
      return readL_;
    }
    
    // optional .expressd.protobuf.ReadAlignment read_r = 4;
    public static final int READ_R_FIELD_NUMBER = 4;
    private expressd.protobuf.Alignments.ReadAlignment readR_;
    public boolean hasReadR() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public expressd.protobuf.Alignments.ReadAlignment getReadR() {
      return readR_;
    }
    public expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadROrBuilder() {
      return readR_;
    }
    
    private void initFields() {
      targetId_ = 0;
      length_ = 0;
      readL_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
      readR_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTargetId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasReadL()) {
        if (!getReadL().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasReadR()) {
        if (!getReadR().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, readL_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, readR_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, targetId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, readL_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, readR_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.FragmentAlignment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(expressd.protobuf.Alignments.FragmentAlignment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements expressd.protobuf.Alignments.FragmentAlignmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return expressd.protobuf.Alignments.internal_static_proto_FragmentAlignment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return expressd.protobuf.Alignments.internal_static_proto_FragmentAlignment_fieldAccessorTable;
      }
      
      // Construct using expressd.protobuf.Alignments.FragmentAlignment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReadLFieldBuilder();
          getReadRFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        targetId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (readLBuilder_ == null) {
          readL_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
        } else {
          readLBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (readRBuilder_ == null) {
          readR_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
        } else {
          readRBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return expressd.protobuf.Alignments.FragmentAlignment.getDescriptor();
      }
      
      public expressd.protobuf.Alignments.FragmentAlignment getDefaultInstanceForType() {
        return expressd.protobuf.Alignments.FragmentAlignment.getDefaultInstance();
      }
      
      public expressd.protobuf.Alignments.FragmentAlignment build() {
        expressd.protobuf.Alignments.FragmentAlignment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private expressd.protobuf.Alignments.FragmentAlignment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        expressd.protobuf.Alignments.FragmentAlignment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public expressd.protobuf.Alignments.FragmentAlignment buildPartial() {
        expressd.protobuf.Alignments.FragmentAlignment result = new expressd.protobuf.Alignments.FragmentAlignment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.targetId_ = targetId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (readLBuilder_ == null) {
          result.readL_ = readL_;
        } else {
          result.readL_ = readLBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (readRBuilder_ == null) {
          result.readR_ = readR_;
        } else {
          result.readR_ = readRBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof expressd.protobuf.Alignments.FragmentAlignment) {
          return mergeFrom((expressd.protobuf.Alignments.FragmentAlignment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(expressd.protobuf.Alignments.FragmentAlignment other) {
        if (other == expressd.protobuf.Alignments.FragmentAlignment.getDefaultInstance()) return this;
        if (other.hasTargetId()) {
          setTargetId(other.getTargetId());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasReadL()) {
          mergeReadL(other.getReadL());
        }
        if (other.hasReadR()) {
          mergeReadR(other.getReadR());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTargetId()) {
          
          return false;
        }
        if (hasReadL()) {
          if (!getReadL().isInitialized()) {
            
            return false;
          }
        }
        if (hasReadR()) {
          if (!getReadR().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              targetId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readUInt32();
              break;
            }
            case 26: {
              expressd.protobuf.Alignments.ReadAlignment.Builder subBuilder = expressd.protobuf.Alignments.ReadAlignment.newBuilder();
              if (hasReadL()) {
                subBuilder.mergeFrom(getReadL());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReadL(subBuilder.buildPartial());
              break;
            }
            case 34: {
              expressd.protobuf.Alignments.ReadAlignment.Builder subBuilder = expressd.protobuf.Alignments.ReadAlignment.newBuilder();
              if (hasReadR()) {
                subBuilder.mergeFrom(getReadR());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReadR(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 target_id = 1;
      private int targetId_ ;
      public boolean hasTargetId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTargetId() {
        return targetId_;
      }
      public Builder setTargetId(int value) {
        bitField0_ |= 0x00000001;
        targetId_ = value;
        onChanged();
        return this;
      }
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        targetId_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 length = 2;
      private int length_ ;
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getLength() {
        return length_;
      }
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }
      
      // optional .expressd.protobuf.ReadAlignment read_l = 3;
      private expressd.protobuf.Alignments.ReadAlignment readL_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder> readLBuilder_;
      public boolean hasReadL() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public expressd.protobuf.Alignments.ReadAlignment getReadL() {
        if (readLBuilder_ == null) {
          return readL_;
        } else {
          return readLBuilder_.getMessage();
        }
      }
      public Builder setReadL(expressd.protobuf.Alignments.ReadAlignment value) {
        if (readLBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readL_ = value;
          onChanged();
        } else {
          readLBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setReadL(
          expressd.protobuf.Alignments.ReadAlignment.Builder builderForValue) {
        if (readLBuilder_ == null) {
          readL_ = builderForValue.build();
          onChanged();
        } else {
          readLBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeReadL(expressd.protobuf.Alignments.ReadAlignment value) {
        if (readLBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              readL_ != expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance()) {
            readL_ =
              expressd.protobuf.Alignments.ReadAlignment.newBuilder(readL_).mergeFrom(value).buildPartial();
          } else {
            readL_ = value;
          }
          onChanged();
        } else {
          readLBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearReadL() {
        if (readLBuilder_ == null) {
          readL_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
          onChanged();
        } else {
          readLBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public expressd.protobuf.Alignments.ReadAlignment.Builder getReadLBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getReadLFieldBuilder().getBuilder();
      }
      public expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadLOrBuilder() {
        if (readLBuilder_ != null) {
          return readLBuilder_.getMessageOrBuilder();
        } else {
          return readL_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder> 
          getReadLFieldBuilder() {
        if (readLBuilder_ == null) {
          readLBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder>(
                  readL_,
                  getParentForChildren(),
                  isClean());
          readL_ = null;
        }
        return readLBuilder_;
      }
      
      // optional .expressd.protobuf.ReadAlignment read_r = 4;
      private expressd.protobuf.Alignments.ReadAlignment readR_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder> readRBuilder_;
      public boolean hasReadR() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public expressd.protobuf.Alignments.ReadAlignment getReadR() {
        if (readRBuilder_ == null) {
          return readR_;
        } else {
          return readRBuilder_.getMessage();
        }
      }
      public Builder setReadR(expressd.protobuf.Alignments.ReadAlignment value) {
        if (readRBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          readR_ = value;
          onChanged();
        } else {
          readRBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setReadR(
          expressd.protobuf.Alignments.ReadAlignment.Builder builderForValue) {
        if (readRBuilder_ == null) {
          readR_ = builderForValue.build();
          onChanged();
        } else {
          readRBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeReadR(expressd.protobuf.Alignments.ReadAlignment value) {
        if (readRBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              readR_ != expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance()) {
            readR_ =
              expressd.protobuf.Alignments.ReadAlignment.newBuilder(readR_).mergeFrom(value).buildPartial();
          } else {
            readR_ = value;
          }
          onChanged();
        } else {
          readRBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearReadR() {
        if (readRBuilder_ == null) {
          readR_ = expressd.protobuf.Alignments.ReadAlignment.getDefaultInstance();
          onChanged();
        } else {
          readRBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public expressd.protobuf.Alignments.ReadAlignment.Builder getReadRBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getReadRFieldBuilder().getBuilder();
      }
      public expressd.protobuf.Alignments.ReadAlignmentOrBuilder getReadROrBuilder() {
        if (readRBuilder_ != null) {
          return readRBuilder_.getMessageOrBuilder();
        } else {
          return readR_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder> 
          getReadRFieldBuilder() {
        if (readRBuilder_ == null) {
          readRBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              expressd.protobuf.Alignments.ReadAlignment, expressd.protobuf.Alignments.ReadAlignment.Builder, expressd.protobuf.Alignments.ReadAlignmentOrBuilder>(
                  readR_,
                  getParentForChildren(),
                  isClean());
          readR_ = null;
        }
        return readRBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:expressd.protobuf.FragmentAlignment)
    }
    
    static {
      defaultInstance = new FragmentAlignment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:expressd.protobuf.FragmentAlignment)
  }
  
  public interface FragmentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // required bool paired = 2;
    boolean hasPaired();
    boolean getPaired();
    
    // repeated .expressd.protobuf.FragmentAlignment alignments = 3;
    java.util.List<expressd.protobuf.Alignments.FragmentAlignment> 
        getAlignmentsList();
    expressd.protobuf.Alignments.FragmentAlignment getAlignments(int index);
    int getAlignmentsCount();
    java.util.List<? extends expressd.protobuf.Alignments.FragmentAlignmentOrBuilder> 
        getAlignmentsOrBuilderList();
    expressd.protobuf.Alignments.FragmentAlignmentOrBuilder getAlignmentsOrBuilder(
        int index);
  }
  public static final class Fragment extends
      com.google.protobuf.GeneratedMessage
      implements FragmentOrBuilder {
    // Use Fragment.newBuilder() to construct.
    private Fragment(Builder builder) {
      super(builder);
    }
    private Fragment(boolean noInit) {}
    
    private static final Fragment defaultInstance;
    public static Fragment getDefaultInstance() {
      return defaultInstance;
    }
    
    public Fragment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return expressd.protobuf.Alignments.internal_static_proto_Fragment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return expressd.protobuf.Alignments.internal_static_proto_Fragment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool paired = 2;
    public static final int PAIRED_FIELD_NUMBER = 2;
    private boolean paired_;
    public boolean hasPaired() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getPaired() {
      return paired_;
    }
    
    // repeated .expressd.protobuf.FragmentAlignment alignments = 3;
    public static final int ALIGNMENTS_FIELD_NUMBER = 3;
    private java.util.List<expressd.protobuf.Alignments.FragmentAlignment> alignments_;
    public java.util.List<expressd.protobuf.Alignments.FragmentAlignment> getAlignmentsList() {
      return alignments_;
    }
    public java.util.List<? extends expressd.protobuf.Alignments.FragmentAlignmentOrBuilder> 
        getAlignmentsOrBuilderList() {
      return alignments_;
    }
    public int getAlignmentsCount() {
      return alignments_.size();
    }
    public expressd.protobuf.Alignments.FragmentAlignment getAlignments(int index) {
      return alignments_.get(index);
    }
    public expressd.protobuf.Alignments.FragmentAlignmentOrBuilder getAlignmentsOrBuilder(
        int index) {
      return alignments_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      paired_ = false;
      alignments_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPaired()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAlignmentsCount(); i++) {
        if (!getAlignments(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, paired_);
      }
      for (int i = 0; i < alignments_.size(); i++) {
        output.writeMessage(3, alignments_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, paired_);
      }
      for (int i = 0; i < alignments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, alignments_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.Fragment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static expressd.protobuf.Alignments.Fragment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(expressd.protobuf.Alignments.Fragment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements expressd.protobuf.Alignments.FragmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return expressd.protobuf.Alignments.internal_static_proto_Fragment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return expressd.protobuf.Alignments.internal_static_proto_Fragment_fieldAccessorTable;
      }
      
      // Construct using expressd.protobuf.Alignments.Fragment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAlignmentsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        paired_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (alignmentsBuilder_ == null) {
          alignments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          alignmentsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return expressd.protobuf.Alignments.Fragment.getDescriptor();
      }
      
      public expressd.protobuf.Alignments.Fragment getDefaultInstanceForType() {
        return expressd.protobuf.Alignments.Fragment.getDefaultInstance();
      }
      
      public expressd.protobuf.Alignments.Fragment build() {
        expressd.protobuf.Alignments.Fragment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private expressd.protobuf.Alignments.Fragment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        expressd.protobuf.Alignments.Fragment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public expressd.protobuf.Alignments.Fragment buildPartial() {
        expressd.protobuf.Alignments.Fragment result = new expressd.protobuf.Alignments.Fragment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.paired_ = paired_;
        if (alignmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            alignments_ = java.util.Collections.unmodifiableList(alignments_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.alignments_ = alignments_;
        } else {
          result.alignments_ = alignmentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof expressd.protobuf.Alignments.Fragment) {
          return mergeFrom((expressd.protobuf.Alignments.Fragment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(expressd.protobuf.Alignments.Fragment other) {
        if (other == expressd.protobuf.Alignments.Fragment.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPaired()) {
          setPaired(other.getPaired());
        }
        if (alignmentsBuilder_ == null) {
          if (!other.alignments_.isEmpty()) {
            if (alignments_.isEmpty()) {
              alignments_ = other.alignments_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAlignmentsIsMutable();
              alignments_.addAll(other.alignments_);
            }
            onChanged();
          }
        } else {
          if (!other.alignments_.isEmpty()) {
            if (alignmentsBuilder_.isEmpty()) {
              alignmentsBuilder_.dispose();
              alignmentsBuilder_ = null;
              alignments_ = other.alignments_;
              bitField0_ = (bitField0_ & ~0x00000004);
              alignmentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAlignmentsFieldBuilder() : null;
            } else {
              alignmentsBuilder_.addAllMessages(other.alignments_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPaired()) {
          
          return false;
        }
        for (int i = 0; i < getAlignmentsCount(); i++) {
          if (!getAlignments(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              paired_ = input.readBool();
              break;
            }
            case 26: {
              expressd.protobuf.Alignments.FragmentAlignment.Builder subBuilder = expressd.protobuf.Alignments.FragmentAlignment.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAlignments(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required bool paired = 2;
      private boolean paired_ ;
      public boolean hasPaired() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getPaired() {
        return paired_;
      }
      public Builder setPaired(boolean value) {
        bitField0_ |= 0x00000002;
        paired_ = value;
        onChanged();
        return this;
      }
      public Builder clearPaired() {
        bitField0_ = (bitField0_ & ~0x00000002);
        paired_ = false;
        onChanged();
        return this;
      }
      
      // repeated .expressd.protobuf.FragmentAlignment alignments = 3;
      private java.util.List<expressd.protobuf.Alignments.FragmentAlignment> alignments_ =
        java.util.Collections.emptyList();
      private void ensureAlignmentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          alignments_ = new java.util.ArrayList<expressd.protobuf.Alignments.FragmentAlignment>(alignments_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          expressd.protobuf.Alignments.FragmentAlignment, expressd.protobuf.Alignments.FragmentAlignment.Builder, expressd.protobuf.Alignments.FragmentAlignmentOrBuilder> alignmentsBuilder_;
      
      public java.util.List<expressd.protobuf.Alignments.FragmentAlignment> getAlignmentsList() {
        if (alignmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alignments_);
        } else {
          return alignmentsBuilder_.getMessageList();
        }
      }
      public int getAlignmentsCount() {
        if (alignmentsBuilder_ == null) {
          return alignments_.size();
        } else {
          return alignmentsBuilder_.getCount();
        }
      }
      public expressd.protobuf.Alignments.FragmentAlignment getAlignments(int index) {
        if (alignmentsBuilder_ == null) {
          return alignments_.get(index);
        } else {
          return alignmentsBuilder_.getMessage(index);
        }
      }
      public Builder setAlignments(
          int index, expressd.protobuf.Alignments.FragmentAlignment value) {
        if (alignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlignmentsIsMutable();
          alignments_.set(index, value);
          onChanged();
        } else {
          alignmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAlignments(
          int index, expressd.protobuf.Alignments.FragmentAlignment.Builder builderForValue) {
        if (alignmentsBuilder_ == null) {
          ensureAlignmentsIsMutable();
          alignments_.set(index, builderForValue.build());
          onChanged();
        } else {
          alignmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAlignments(expressd.protobuf.Alignments.FragmentAlignment value) {
        if (alignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlignmentsIsMutable();
          alignments_.add(value);
          onChanged();
        } else {
          alignmentsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAlignments(
          int index, expressd.protobuf.Alignments.FragmentAlignment value) {
        if (alignmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlignmentsIsMutable();
          alignments_.add(index, value);
          onChanged();
        } else {
          alignmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAlignments(
          expressd.protobuf.Alignments.FragmentAlignment.Builder builderForValue) {
        if (alignmentsBuilder_ == null) {
          ensureAlignmentsIsMutable();
          alignments_.add(builderForValue.build());
          onChanged();
        } else {
          alignmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAlignments(
          int index, expressd.protobuf.Alignments.FragmentAlignment.Builder builderForValue) {
        if (alignmentsBuilder_ == null) {
          ensureAlignmentsIsMutable();
          alignments_.add(index, builderForValue.build());
          onChanged();
        } else {
          alignmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAlignments(
          java.lang.Iterable<? extends expressd.protobuf.Alignments.FragmentAlignment> values) {
        if (alignmentsBuilder_ == null) {
          ensureAlignmentsIsMutable();
          super.addAll(values, alignments_);
          onChanged();
        } else {
          alignmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAlignments() {
        if (alignmentsBuilder_ == null) {
          alignments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          alignmentsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAlignments(int index) {
        if (alignmentsBuilder_ == null) {
          ensureAlignmentsIsMutable();
          alignments_.remove(index);
          onChanged();
        } else {
          alignmentsBuilder_.remove(index);
        }
        return this;
      }
      public expressd.protobuf.Alignments.FragmentAlignment.Builder getAlignmentsBuilder(
          int index) {
        return getAlignmentsFieldBuilder().getBuilder(index);
      }
      public expressd.protobuf.Alignments.FragmentAlignmentOrBuilder getAlignmentsOrBuilder(
          int index) {
        if (alignmentsBuilder_ == null) {
          return alignments_.get(index);  } else {
          return alignmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends expressd.protobuf.Alignments.FragmentAlignmentOrBuilder> 
           getAlignmentsOrBuilderList() {
        if (alignmentsBuilder_ != null) {
          return alignmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alignments_);
        }
      }
      public expressd.protobuf.Alignments.FragmentAlignment.Builder addAlignmentsBuilder() {
        return getAlignmentsFieldBuilder().addBuilder(
            expressd.protobuf.Alignments.FragmentAlignment.getDefaultInstance());
      }
      public expressd.protobuf.Alignments.FragmentAlignment.Builder addAlignmentsBuilder(
          int index) {
        return getAlignmentsFieldBuilder().addBuilder(
            index, expressd.protobuf.Alignments.FragmentAlignment.getDefaultInstance());
      }
      public java.util.List<expressd.protobuf.Alignments.FragmentAlignment.Builder> 
           getAlignmentsBuilderList() {
        return getAlignmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          expressd.protobuf.Alignments.FragmentAlignment, expressd.protobuf.Alignments.FragmentAlignment.Builder, expressd.protobuf.Alignments.FragmentAlignmentOrBuilder> 
          getAlignmentsFieldBuilder() {
        if (alignmentsBuilder_ == null) {
          alignmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              expressd.protobuf.Alignments.FragmentAlignment, expressd.protobuf.Alignments.FragmentAlignment.Builder, expressd.protobuf.Alignments.FragmentAlignmentOrBuilder>(
                  alignments_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          alignments_ = null;
        }
        return alignmentsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:expressd.protobuf.Fragment)
    }
    
    static {
      defaultInstance = new Fragment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:expressd.protobuf.Fragment)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReadAlignment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ReadAlignment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_FragmentAlignment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_FragmentAlignment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Fragment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Fragment_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/alignments.proto\022\005proto\"t\n\rReadA" +
      "lignment\022\r\n\005first\030\001 \002(\010\022\020\n\010left_pos\030\002 \001(" +
      "\r\022\021\n\tright_pos\030\003 \001(\r\022\030\n\020mismatch_indices" +
      "\030\004 \001(\014\022\025\n\rmismatch_nucs\030\005 \001(\014\"\202\001\n\021Fragme" +
      "ntAlignment\022\021\n\ttarget_id\030\001 \002(\r\022\016\n\006length" +
      "\030\002 \001(\r\022$\n\006read_l\030\003 \001(\0132\024.expressd.protobuf.ReadAlign" +
      "ment\022$\n\006read_r\030\004 \001(\0132\024.expressd.protobuf.ReadAlignme" +
      "nt\"V\n\010Fragment\022\014\n\004name\030\001 \001(\t\022\016\n\006paired\030\002" +
      " \002(\010\022,\n\nalignments\030\003 \003(\0132\030.expressd.protobuf.Fragmen" +
      "tAlignment"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_ReadAlignment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_ReadAlignment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_ReadAlignment_descriptor,
              new java.lang.String[] { "First", "LeftPos", "RightPos", "MismatchIndices", "MismatchNucs", },
              expressd.protobuf.Alignments.ReadAlignment.class,
              expressd.protobuf.Alignments.ReadAlignment.Builder.class);
          internal_static_proto_FragmentAlignment_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_FragmentAlignment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_FragmentAlignment_descriptor,
              new java.lang.String[] { "TargetId", "Length", "ReadL", "ReadR", },
              expressd.protobuf.Alignments.FragmentAlignment.class,
              expressd.protobuf.Alignments.FragmentAlignment.Builder.class);
          internal_static_proto_Fragment_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_proto_Fragment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Fragment_descriptor,
              new java.lang.String[] { "Name", "Paired", "Alignments", },
              expressd.protobuf.Alignments.Fragment.class,
              expressd.protobuf.Alignments.Fragment.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
